protocol = "net_observer"
metrics_port = 3000

provider = "NirvanaLab"
region = "San"
instance = "zenrock-new"

interval_seconds = 30
mtr_count = 5
mtr_max_hops = 30
mtr_timeout_seconds = 15

[[targets]]
address = "8.8.8.8"
class_name = "public"
location = "California"
provider = "google"

[[targets]]
address = "1.1.1.1"
class_name = "public"
location = "Queensland"
provider = "cloudflare"

[[targets]]
address = "34.86.142.37"
class_name = "cross_region"
location = "Washington"
provider = "google"

[[targets]]
address = "185.209.179.155"
class_name = "critical"
location = "NYC"
provider = "latitude"

[[targets]]
address = "103.219.171.153"
class_name = "critical"
location = "Frankfurt"
provider = "latitude"

[[targets]]
address = "64.34.85.31"
class_name = "critical"
location = "Frankfurt2"
provider = "latitude"

[[targets]]
address = "57.129.83.10"
class_name = "critical"
location = "Limburg"
provider = "ovh"

[[targets]]
address = "67.213.127.51"
class_name = "critical"
location = "Amsterdam"
provider = "latitude"

[[targets]]
address = "185.26.9.113"
class_name = "critical"
location = "ASH"
provider = "latitude"
